version: "3.7"
services:
  backend:
    build:
      #the context is where u specify the path
      #this path is where the docker app is basically examining
      context: ./myProjectVtAceIt
      #need to also mention the dockerfile
      #this docker file is inside
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - vtaceit-network
  frontend:
    build:
      #this context is basically what the docker application is looking at
      context: ./vtaceit-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - vtaceit-network
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: vtaceit_docker
    ports:
      - "5432:5432"
    networks:
      - vtaceit-network
    volumes:
      - vtaceit-data:/var/lib/postgresql/data
networks:
  vtaceit-network:
    driver: bridge
volumes:
  vtaceit-data: